require(Hmisc)
require(magrittr)
require(reshape2)
require(plyr)
require(dplyr)
require(kableExtra)
require(ggplot2)
require(GGally)
require(broman)
require(sna)
require(readr)
require(lubridate)
require(stringr)
require(plotly)
require(network)
# require(igraph)
require(visNetwork)
require(ggraph)
require(tidygraph)
# require(RNeo4j)
require(bit64)
require(pdftools)
require(Ckmeans.1d.dp)
require(english)